### ISSUE TITLE
please create sd for recovery 

### ISSUE THREAD

**Issue by maxbit-me** [wladimir-computin/FimiX8-SDFG#10]
hello and congratulations for your work, I can not create a sd to restore many drones, many users have this problem and we do not know how to solve. I would ask you if you can create a file so we put it in the sd card to restore the drone. Thank you
P.S. I inserted in the root of the sd of the drone fr_firmware.bin without any benefit .. surely we miss some steps

**Comment by k2dp2k** [comment]
@maxbit-me have you got such a firmware file? or why is this topic closed?
