### ISSUE TITLE
New backend API 

### ISSUE THREAD

**Issue by xviews** [wladimir-computin/FimiX8-SDFG#3]
Hi Wladimir!
Thanks for your job!

old backend API is down
"404 Not Found: Requested route ('fimiapp-server-frankfurt.mi-ae.com.de') does not exist."

i can find only this link
https://fmapp.mi-ae.cn/v3/firmware/getFirmwareDetail
and
https://fimiservice-newus.mi-ae.com/v3/firmware/getFirmwareDetail <- I think it is the right one

**Comment by wladimir-computin** [comment]
yep, you're right! Thanks, I will update the link.

**Comment by xviews** [comment]
> yep, you're right! Thanks, I will update the link.

Servus, kannst du auch die X8UpdateGenerator-1.0.jar updaten? Hatte den Link zum Server schon in den Files gefunden, nur das compilen wollte nicht so richtig ^^

**Comment by wladimir-computin** [comment]
Done :)
