### ISSUE TITLE
the backend url link dont work

### ISSUE THREAD

**Issue by oneyesoneno** [wladimir-computin/FimiX8-SDFG#9]
https://fimiapp-server-frankfurt.mi-ae.com.de/v3/firmware/getFirmwareDetail pls help this link broken.. ty

**Comment by PikoMeter** [comment]
I got it to work using a tunneling vpn service. 
Try that if you are struggling.
If it doesnt work i can upload json or whatever images directly for you
cheers

**Comment by emilieandthebee** [comment]
Hi there! 
Great project, willing to contribute.
I do confirm the firmware URL is not working anymore.
There should be a change, if anyone get it, please update.
Last will be de decompile the latest APP to get the new URL info

**Comment by xviews** [comment]
Hey, the new link is already available in the app since 28 October.
https://fimiservice-newus.mi-ae.com/v3/firmware/getFirmwareDetail
I think you need to compile it by yourself
[Update.zip](https://github.com/wladimir-computin/FimiX8-SDFG/files/4080155/Update.zip)

**Comment by wladimir-computin** [comment]
Fixed
